version: "3.1"

services:
  database:
    image: dockersamples/atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    ports:
      - "5432:5432"
    networks:
      - back-tier
    secrets:
      - postgres_password

  appserver:
    image: dockersamples/atsea_app
    container_name: atsea
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 15s
      timeout: 10s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cucumber_tests
    tty: true
    environment:
      - BASE_URI=http://atsea:8080
      - BASE_API_URI=http://atsea:8080/api
      - browser=chrome
      - rp_output_type=console_detailed
      - PLAYWRIGHT_CLI_EXECUTABLE_PATH=npx playwright
      - HOST_HAS_GUI=false
    networks:
      - front-tier

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay

secrets:
  postgres_password:
    file: ./pg_psw